<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="NLog" Version="6.1.2" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.26.200" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
  </ItemGroup>

</Project>
